# NUMPY MATEMATİKSEL İŞLEMLER

**1. Önceki derste kaydettiğiniz diziyi diskten yükleyin**

In [2]:
import numpy as np
import pandas as pd

In [3]:
DF1=pd.read_csv("data1.csv")

DF2=np.array(DF1)

print(DF1)
print(DF1.shape)
print("veri dizisi:")
print(DF2)


      Unnamed: 0       0    1    2    3    4        5        6      7    8  \
0              0     1.0  1.0  1.0  1.0  1.0   1.0000   1.0000   1.00  1.0   
1              1     2.0  0.0  0.0  0.0  0.0  37.6878  37.4016  10.27  0.0   
2              2     3.0  0.0  0.0  0.0  0.0  37.2003  30.4376  78.07  0.0   
3              3     4.0  0.0  0.0  0.0  0.0  35.6846  26.7266  42.77  0.0   
4              4     5.0  0.0  0.0  0.0  0.0  36.4171  28.6991  14.86  0.0   
...          ...     ...  ...  ...  ...  ...      ...      ...    ...  ...   
6568        6568  6569.0  6.0  0.0  2.0  0.0  38.1200  31.2900  10.00  0.0   
6569        6569  6570.0  5.0  0.0  2.0  0.0  37.8300  27.7100  10.00  0.0   
6570        6570  6571.0  4.0  0.0  2.0  0.0  37.6300  37.3700  10.00  0.0   
6571        6571  6572.0  3.0  0.0  2.0  0.0  39.5400  26.1400  10.00  0.0   
6572        6572  6573.0  2.0  0.0  2.0  0.0  37.7900  28.2100  10.00  0.0   

        9   10   11   12   13   14  
0     1.0  1.0  1.0  1.0  

**2. Her sütun için ortalama ve standart sapmayı görüntüleyin.**

In [4]:
print(np.mean(DF2))
print(np.std(DF2))


761.9583082477561
2024.5709293064842


**3. Sırayla sütunlardan 1, 25, 25, 10, 4 çıkarın. (Bir satır kodda çıkarılabileceğini unutmayın.)**

In [5]:
DF2-1


array([[-1.000e+00,  0.000e+00,  0.000e+00, ...,  0.000e+00,  0.000e+00,
         0.000e+00],
       [ 0.000e+00,  1.000e+00, -1.000e+00, ...,  3.400e+00,  6.000e+00,
        -1.000e+00],
       [ 1.000e+00,  2.000e+00, -1.000e+00, ...,  3.000e+00,  6.000e+00,
        -1.000e+00],
       ...,
       [ 6.569e+03,  6.570e+03,  3.000e+00, ...,  3.800e+00,  1.000e+00,
        -1.000e+00],
       [ 6.570e+03,  6.571e+03,  2.000e+00, ...,  4.200e+00,  1.000e+00,
        -1.000e+00],
       [ 6.571e+03,  6.572e+03,  1.000e+00, ...,  3.400e+00,  1.000e+00,
        -1.000e+00]])

In [6]:
DF2-25

array([[ -25. ,  -24. ,  -24. , ...,  -24. ,  -24. ,  -24. ],
       [ -24. ,  -23. ,  -25. , ...,  -20.6,  -18. ,  -25. ],
       [ -23. ,  -22. ,  -25. , ...,  -21. ,  -18. ,  -25. ],
       ...,
       [6545. , 6546. ,  -21. , ...,  -20.2,  -23. ,  -25. ],
       [6546. , 6547. ,  -22. , ...,  -19.8,  -23. ,  -25. ],
       [6547. , 6548. ,  -23. , ...,  -20.6,  -23. ,  -25. ]])

In [7]:
DF2-10

array([[-1.000e+01, -9.000e+00, -9.000e+00, ..., -9.000e+00, -9.000e+00,
        -9.000e+00],
       [-9.000e+00, -8.000e+00, -1.000e+01, ..., -5.600e+00, -3.000e+00,
        -1.000e+01],
       [-8.000e+00, -7.000e+00, -1.000e+01, ..., -6.000e+00, -3.000e+00,
        -1.000e+01],
       ...,
       [ 6.560e+03,  6.561e+03, -6.000e+00, ..., -5.200e+00, -8.000e+00,
        -1.000e+01],
       [ 6.561e+03,  6.562e+03, -7.000e+00, ..., -4.800e+00, -8.000e+00,
        -1.000e+01],
       [ 6.562e+03,  6.563e+03, -8.000e+00, ..., -5.600e+00, -8.000e+00,
        -1.000e+01]])

In [8]:
DF2-4

array([[-4.000e+00, -3.000e+00, -3.000e+00, ..., -3.000e+00, -3.000e+00,
        -3.000e+00],
       [-3.000e+00, -2.000e+00, -4.000e+00, ...,  4.000e-01,  3.000e+00,
        -4.000e+00],
       [-2.000e+00, -1.000e+00, -4.000e+00, ...,  0.000e+00,  3.000e+00,
        -4.000e+00],
       ...,
       [ 6.566e+03,  6.567e+03,  0.000e+00, ...,  8.000e-01, -2.000e+00,
        -4.000e+00],
       [ 6.567e+03,  6.568e+03, -1.000e+00, ...,  1.200e+00, -2.000e+00,
        -4.000e+00],
       [ 6.568e+03,  6.569e+03, -2.000e+00, ...,  4.000e-01, -2.000e+00,
        -4.000e+00]])

**4. Her bir öğeyi 2 ile çarpın. (Bir kod satırında çarpılabileceğini unutmayın.)**

In [6]:
print(DF2 * 2)

[[0.0000e+00 2.0000e+00 2.0000e+00 ... 2.0000e+00 2.0000e+00 2.0000e+00]
 [2.0000e+00 4.0000e+00 0.0000e+00 ... 8.8000e+00 1.4000e+01 0.0000e+00]
 [4.0000e+00 6.0000e+00 0.0000e+00 ... 8.0000e+00 1.4000e+01 0.0000e+00]
 ...
 [1.3140e+04 1.3142e+04 8.0000e+00 ... 9.6000e+00 4.0000e+00 0.0000e+00]
 [1.3142e+04 1.3144e+04 6.0000e+00 ... 1.0400e+01 4.0000e+00 0.0000e+00]
 [1.3144e+04 1.3146e+04 4.0000e+00 ... 8.8000e+00 4.0000e+00 0.0000e+00]]
